---
params:
    batch_size: 12
    epoch: 100
    lr: 0.0001
    decay: 0.1
    decay_step: 5

save:
    metapath: "D:\\model\\PureGaze"
    folder: gaze360
    name: eth
    step: 10

data:
    image: "D:/gaze_estimate/dataset/FaceBased/Gaze360/Image"
    label: "D:/gaze_estimate/dataset/FaceBased/Gaze360/Label/train.label"
    header: True
    name: gaze360
    isFolder: False

pretrain: False
device: 0
reader: reader_adap
map: "D:\\gaze_estimate\\PureGaze\\Masker\\360-masker.jpg"
